name = "image-extract-app"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "image-extract-bucket"

[[d1_databases]]
binding = "DB"
database_name = "image-extract-db"
database_id = "ca83d65b-bbb8-44b7-a3f4-c494bc4ae1c2"
